// Copyright 2021 github.com/gagliardetto
// This file has been modified by github.com/gagliardetto
//
// Copyright 2020 dfuse Platform Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package rpc

import (
	"context"
	"encoding/base64"
	"fmt"

	"github.com/gagliardetto/solana-go"
)

type SimulateTransactionResponse struct {
	RPCContext
	Value *SimulateTransactionResult `json:"value"`
}

type SimulateTransactionResult struct {
	// Error if transaction failed, null if transaction succeeded.
	Err any `json:"err,omitempty"`

	// Array of log messages the transaction instructions output during execution,
	// null if simulation failed before the transaction was able to execute
	// (for example due to an invalid blockhash or signature verification failure)
	Logs []string `json:"logs,omitempty"`

	// Array of accounts with the same length as the accounts.addresses array in the request.
	Accounts []*Account `json:"accounts"`

	// The number of compute budget units consumed during the processing of this transaction.
	UnitsConsumed *uint64 `json:"unitsConsumed,omitempty"`

	// The size of loaded accounts data in bytes.
	LoadedAccountsDataSize *uint32 `json:"loadedAccountsDataSize,omitempty"`

	// The most-recent return data generated by an instruction in the transaction.
	ReturnData *ReturnData `json:"returnData,omitempty"`

	// If innerInstructions were requested, a list of inner instructions.
	InnerInstructions []InnerInstruction `json:"innerInstructions,omitempty"`

	// The replacement blockhash used when replaceRecentBlockhash is true.
	ReplacementBlockhash *ReplacementBlockhash `json:"replacementBlockhash,omitempty"`

	// Fee this transaction was charged.
	Fee *uint64 `json:"fee,omitempty"`

	// Array of u64 account balances from before the transaction was processed.
	PreBalances []uint64 `json:"preBalances,omitempty"`

	// Array of u64 account balances after the transaction was processed.
	PostBalances []uint64 `json:"postBalances,omitempty"`

	// List of token balances from before the transaction was processed.
	PreTokenBalances []TokenBalance `json:"preTokenBalances,omitempty"`

	// List of token balances from after the transaction was processed.
	PostTokenBalances []TokenBalance `json:"postTokenBalances,omitempty"`

	// Addresses loaded from address lookup tables.
	LoadedAddresses *LoadedAddresses `json:"loadedAddresses,omitempty"`
}

type ReplacementBlockhash struct {
	Blockhash            solana.Hash `json:"blockhash"`
	LastValidBlockHeight uint64      `json:"lastValidBlockHeight"`
}

// SimulateTransaction simulates sending a transaction.
func (cl *Client) SimulateTransaction(
	ctx context.Context,
	transaction *solana.Transaction,
) (out *SimulateTransactionResponse, err error) {
	return cl.SimulateTransactionWithOpts(
		ctx,
		transaction,
		nil,
	)
}

type SimulateTransactionOpts struct {
	// If true the transaction signatures will be verified
	// (default: false, conflicts with ReplaceRecentBlockhash)
	SigVerify bool

	// Commitment level to simulate the transaction at.
	// (default: "finalized").
	Commitment CommitmentType

	// If true the transaction recent blockhash will be replaced with the most recent blockhash.
	// (default: false, conflicts with SigVerify)
	ReplaceRecentBlockhash bool

	// If true the response will include inner instructions.
	// These inner instructions will be jsonParsed where possible,
	// otherwise json. (default: false)
	InnerInstructions bool

	// The minimum slot that the request can be evaluated at.
	MinContextSlot *uint64

	Accounts *SimulateTransactionAccountsOpts
}

type SimulateTransactionAccountsOpts struct {
	// (optional) Encoding for returned Account data,
	// either "base64" (default), "base64+zstd" or "jsonParsed".
	// - "jsonParsed" encoding attempts to use program-specific state parsers
	//   to return more human-readable and explicit account state data.
	//   If "jsonParsed" is requested but a parser cannot be found,
	//   the field falls back to binary encoding, detectable when
	//   the data field is type <string>.
	Encoding solana.EncodingType

	// An array of accounts to return.
	Addresses []solana.PublicKey
}

// SimulateTransaction simulates sending a transaction.
func (cl *Client) SimulateTransactionWithOpts(
	ctx context.Context,
	transaction *solana.Transaction,
	opts *SimulateTransactionOpts,
) (out *SimulateTransactionResponse, err error) {
	txData, err := transaction.MarshalBinary()
	if err != nil {
		return nil, fmt.Errorf("send transaction: encode transaction: %w", err)
	}
	return cl.SimulateRawTransactionWithOpts(ctx, txData, opts)
}

func (cl *Client) SimulateRawTransactionWithOpts(
	ctx context.Context,
	txData []byte,
	opts *SimulateTransactionOpts,
) (out *SimulateTransactionResponse, err error) {
	obj := M{
		"encoding": "base64",
	}
	if opts != nil {
		if opts.SigVerify {
			obj["sigVerify"] = opts.SigVerify
		}
		if opts.Commitment != "" {
			obj["commitment"] = opts.Commitment
		}
		if opts.ReplaceRecentBlockhash {
			obj["replaceRecentBlockhash"] = opts.ReplaceRecentBlockhash
		}
		if opts.InnerInstructions {
			obj["innerInstructions"] = opts.InnerInstructions
		}
		if opts.MinContextSlot != nil {
			obj["minContextSlot"] = *opts.MinContextSlot
		}
		if opts.Accounts != nil {
			obj["accounts"] = M{
				"encoding":  opts.Accounts.Encoding,
				"addresses": opts.Accounts.Addresses,
			}
		}
	}

	b64Data := base64.StdEncoding.EncodeToString(txData)
	params := []any{
		b64Data,
		obj,
	}

	err = cl.rpcClient.CallForInto(ctx, &out, "simulateTransaction", params)
	return
}
