on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/lint.yml"
name: lint
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4
          args: --timeout=10m
